# Generated by Django 2.2.5 on 2019-10-05 20:31

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_auto_20191005_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='QandAModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Questions', models.CharField(max_length=1000)),
                ('Answers', multiselectfield.db.fields.MultiSelectField(blank=True, max_length=200)),
            ],
        ),
    ]
