# Generated by Django 2.2.5 on 2019-10-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_qandamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qandamodel',
            name='Answers',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
